# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v8.4.2
_src_path: gh:Tecnativa/doodba-copier-template
backup_dst: ""
cidr_whitelist: null
domains_prod: {}
domains_test: {}
gitlab_url: ""
odoo_dbfilter: ^prod
odoo_initial_lang: es_ES
odoo_listdb: false
odoo_listdb_staging: false
odoo_oci_image: ""
odoo_proxy: ""
odoo_version: 17.0
paths_with_crawlers:
  - /web/image/website
paths_without_crawlers:
  - /web
  - /website/info
postgres_dbname: prod
postgres_exposed: false
postgres_username: odoo
postgres_version: "16"
project_author: Victor
project_license: LGPL-3.0-or-later
project_name: myproject-odoo
smtp_default_from: ""
smtp_relay_host: ""
